spring:
  application:
    name: wolverine-service
  datasource: #定义数据源
    url: jdbc:mysql://127.0.0.1:3306/qiyu?serverTimezone=GMT%2B8&useSSL=FALSE&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password: 12345678
      timeout: 3000 # 连接超时时间（毫秒）
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接

server:
  servlet:
    context-path: /wolverine

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/db/*.xml
  global-config:
    db-config:
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

nebula:
  ngbatis:
    session-life-length: 300000
    check-fixed-rate: 300000
    use-session-pool: true
  hosts: 127.0.0.1:9669
  username: root
  password: nebula
  space: qiyu
  pool-config:
    min-conns-size: 3
    max-conns-size: 10
    timeout: 0
    idle-time: 0
    interval-idle: -1
    wait-time: 0
    min-cluster-health-rate: 1.0
    enable-ssl: false

cql:
  parser:
    mapper-locations: mapper/graph/*.xml

logging:
  level:
    org.nebula.contrib: DEBUG

common:
  executor:
    core-size: 3
    max-size: 6
