spring:
  application:
    name: wolverine-service
  datasource: #定义数据源
    url: jdbc:mysql://127.0.0.1:3306/qiyu?serverTimezone=GMT%2B8&useSSL=FALSE&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource

server:
  servlet:
    context-path: /wolverine

# mybatis-plus相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      db-type: MYSQL
  configuration:
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

nebula:
  ngbatis:
    session-life-length: 300000
    check-fixed-rate: 300000
    use-session-pool: true
  hosts: 127.0.0.1:19669, 127.0.0.1:9669
  username: root
  password: nebula
  space: test
  pool-config:
    min-conns-size: 0
    max-conns-size: 10
    timeout: 0
    idle-time: 0
    interval-idle: -1
    wait-time: 0
    min-cluster-health-rate: 1.0
    enable-ssl: false